config/routes.rb
Todone::Application.routes.draw do
  resources :tasks
  root to: 'tasks#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	def index
		@task = Task.new
		@tasks = Task.all
	end

	def create
		@task = Task.new(task_params)
		if @task.save!
			flash[:info] = "Added task: #{@task.name}"
			
		redirect_to tasks_path
		end
	end

	def destroy
		@task = Task.find(params[:id])
		@task.destroy
		flash[:info] = "Done"

		redirect_to tasks_path
	end



	private

	def task_params
			params.require(:task).permit(:name)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todone</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no'>"
</head>
<body>
	<nav class='navbar navbar-default'>
		<a class='navbar-brand' href='/'>ToDone</a>
		<ul class='nav navbar-nav'>
			<li><%= link_to "Tasks", tasks_path %></li>
		</ul>
	</nav>

<div class="container">
	<% if flash[:info] %>
		<div class='alert alert-info'>
		<%= flash[:info] %>
	</div>
	<% end %>

<%= yield %>
</div>

</body>
</html>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<ul class='list-group'>
	<% @tasks.each do |task| %>
	<li class='list-group-item clearfix'>
		<%= task.name %>
		<%= link_to "Done", task_path(task), method: :delete, class: 'btn btn-danger pull-right' %>
	</li>
	<% end %>
</ul>

<div class='jumbotron'>
	<h3>New Task</h3>

	<%= simple_form_for @task do |form| %>
		<%= form.input :name, label: false %><br>
		<%= form.submit "Add", class: 'btn btn-primary' %>
	<% end %>
</div>